language: node_js
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-cran-rserve
node_js:
  - "10"
  - "9"
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v1.0.4"
  - "iojs-v1.1.0"
  - "iojs-v1.2.0"
  - "iojs-v1.3.0"
  - "iojs-v1.4.3"
  - "iojs-v1.5.1"
  - "iojs-v1.6.1"
  - "iojs-v1.7.1"
  - "iojs-v1.8.4"
  - "iojs-v2.5.0"
  - "iojs-v3.3.1"
